### ISSUE TITLE
Error in plone /@@user-information?user_id=TestUser on IE

### ISSUE THREAD

**Issue by GhitaB** [zopefoundation/zope.formlib#17]
The solution implemented here:
https://github.com/zopefoundation/z3c.form/commit/b5a2d0e819ebab906fad13a18e8602f02a53ae5c

to be copied here:
https://github.com/zopefoundation/zope.formlib/blob/master/src/zope/formlib/orderedSelectionList.pt#L115

in order to fix the same erorr on IE:
as reported here: https://github.com/zopefoundation/z3c.form/issues/23
as solved in this merge: https://github.com/zopefoundation/z3c.form/pull/37

**Comment by mgedmin** [comment]
Sounds reasonable!  Would you like to create a pull request?  (You can do it through the web using GitHub's built-in editor.)

**Comment by GhitaB** [comment]
Done here: https://github.com/zopefoundation/zope.formlib/pull/18

Do you have any idea when the new version will be released? I tried without success an override in this case. Sure, I can use my fork, but... :) (https://stackoverflow.com/questions/52521177/override-monkey-patch-template-of-external-class)

**Comment by mgedmin** [comment]
Should be fixed in zope.formlib 4.5.0, which is out on PyPI.

Thanks!
